name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"

      - name: Install PHP dependencies
        run: |
          if [ -f composer.lock ]; then
            composer install
          else
            echo "No composer.lock file found, skipping PHP dependencies installation."
          fi

      - name: Run PHP tests
        run: |
          if [ -f vendor/bin/phpunit ]; then
            vendor/bin/phpunit
          else
            echo "No PHPUnit found, skipping PHP tests."
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Node.js dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            echo "No package-lock.json file found, skipping Node.js dependencies installation."
          fi

      - name: Run Node.js tests
        run: |
          if [ -f package.json ] && grep -q '"test"' package.json; then
            npm test
          else
            echo "No test script found in package.json, skipping Node.js tests."
          fi
